-- ============================================================================
-- Migration 006: Contact Messages
-- ============================================================================
-- Purpose: Store contact-form submissions read by /dashboard/messages
-- Created: 2026-09-25
-- Dependencies: 001_core_schema.sql (users table, update_updated_at function)
-- Rollback: rollback_006_messages.sql
-- Version: 1.0
-- ============================================================================
-- The `messages` table is the only table the database abstraction layer
-- (src/libs/database.ts) touches, so a fresh Supabase project needs this
-- migration before the contact form or the messages dashboard can work.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- PART 1: TABLE
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS messages (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Optional author links. The contact form is public, so both stay NULL for
    -- anonymous submissions.
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    clerk_user_id text,

    -- Submitted content
    name text NOT NULL,
    email text NOT NULL,
    subject text,
    message text NOT NULL,

    -- Dashboard state
    is_read boolean NOT NULL DEFAULT false,
    is_archived boolean NOT NULL DEFAULT false,

    -- Request metadata captured by the API route
    ip_address text,
    user_agent text,

    -- Timestamps. Defaults let an insert omit them; a seed or import may set
    -- them explicitly to keep the original submission date.
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- PART 2: INDEXES
-- ----------------------------------------------------------------------------

-- The dashboard lists newest first and filters on the two state flags.
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_is_read ON messages(is_read);
CREATE INDEX IF NOT EXISTS idx_messages_is_archived ON messages(is_archived);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON messages(user_id);

-- ----------------------------------------------------------------------------
-- PART 3: TRIGGERS
-- ----------------------------------------------------------------------------

-- Same helper as 001; repeated here so this migration also applies on a
-- database where 001 ran before the function was added.
-- Security: SET search_path prevents search_path injection attacks
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS messages_updated_at ON messages;

CREATE TRIGGER messages_updated_at
    BEFORE UPDATE ON messages
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ----------------------------------------------------------------------------
-- PART 4: ROW LEVEL SECURITY
-- ----------------------------------------------------------------------------

-- Messages hold personal data (email, IP address, user agent), so the table is
-- closed by default: only the service role reaches it, which is how the API
-- routes and the dashboard read and write messages. Enabling RLS without a
-- policy for anon or authenticated denies those roles every operation.
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "messages_service_all" ON messages;

-- Performance: SELECT wrapper ensures auth.role() evaluated once per query, not per row
CREATE POLICY "messages_service_all" ON messages
    FOR ALL
    USING ((select auth.role()) = 'service_role');

-- ----------------------------------------------------------------------------
-- PART 5: DOCUMENTATION
-- ----------------------------------------------------------------------------

COMMENT ON TABLE messages IS 'Contact-form submissions; read and written through src/libs/database.ts';
COMMENT ON COLUMN messages.user_id IS 'Author in the users table, NULL for anonymous submissions';
COMMENT ON COLUMN messages.clerk_user_id IS 'Clerk user id of the author, NULL for anonymous submissions';
COMMENT ON COLUMN messages.is_read IS 'Marked by the messages dashboard';
COMMENT ON COLUMN messages.is_archived IS 'Marked by the messages dashboard; archived messages are hidden by default';

-- ----------------------------------------------------------------------------
-- PART 6: MIGRATION TRACKING
-- ----------------------------------------------------------------------------

-- Only when 005_migration_tracking.sql has been applied.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'schema_migrations'
    ) THEN
        INSERT INTO schema_migrations (version, name)
        VALUES ('006', 'messages')
        ON CONFLICT (version) DO NOTHING;
    END IF;
END$$;

-- ----------------------------------------------------------------------------
-- PART 7: VERIFICATION
-- ----------------------------------------------------------------------------

DO $$
DECLARE
    v_column_count INTEGER;
    v_rls_enabled BOOLEAN;
BEGIN
    SELECT COUNT(*) INTO v_column_count
    FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'messages'
    AND column_name IN (
        'id', 'user_id', 'clerk_user_id', 'name', 'email', 'subject', 'message',
        'is_read', 'is_archived', 'ip_address', 'user_agent', 'created_at', 'updated_at'
    );

    SELECT relrowsecurity INTO v_rls_enabled
    FROM pg_class
    WHERE oid = 'public.messages'::regclass;

    IF v_column_count <> 13 THEN
        RAISE EXCEPTION 'Migration 006 verification failed: expected 13 columns, found %', v_column_count;
    END IF;

    IF NOT v_rls_enabled THEN
        RAISE EXCEPTION 'Migration 006 verification failed: row level security is not enabled on messages';
    END IF;

    RAISE NOTICE '';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'Migration 006 completed successfully!';
    RAISE NOTICE '  - messages table with 13 columns';
    RAISE NOTICE '  - 4 indexes for the dashboard queries';
    RAISE NOTICE '  - updated_at trigger';
    RAISE NOTICE '  - RLS enabled, service role only';
    RAISE NOTICE '========================================';
END$$;

COMMIT;
