name: Bug Report
description: Report a bug or issue in astro-basics
title: 'fix: '
labels: ['bug', 'p2-high']
projects: ['shawn-sandy/1']
assignees:
  - shawn-sandy

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what the bug is...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images here, or paste links...
    validations:
      required: false

  - type: dropdown
    id: component-type
    attributes:
      label: Component Type
      description: What type of component is affected?
      options:
        - Astro Component
        - React Component
        - SCSS/Styling
        - Build System
        - Authentication
        - Testing
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - p1-critical (Blocks development/production)
        - p2-high (Major functionality broken)
        - p3-medium (Minor functionality issue)
        - p4-low (Cosmetic/nice-to-have)
      default: 1
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details where the bug occurs
      placeholder: |
        - OS: [e.g. macOS 13.0]
        - Browser: [e.g. Chrome 108.0]
        - Node version: [e.g. 18.12.0]
        - Astro version: [e.g. 5.12.3]
        - Package version: [e.g. 0.1.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or console output
      render: shell
      placeholder: Paste any error messages or console output here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...
    validations:
      required: false
