/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file was generated by scripts/setup-roles.ts
 * Source: config/roles.config.ts
 * Generated: 2025-10-10T12:07:49.603Z
 *
 * To modify roles, edit config/roles.config.ts and run:
 *   npm run setup:roles
 *
 * @module types/generated-roles
 */

/**
 * User role type
 *
 * Represents all available user roles in the application.
 * This type is generated from the role configuration.
 */
export type UserRole = 'member' | 'admin' | 'super_admin'

/**
 * Array of all valid user roles
 *
 * Use this for runtime validation and iteration.
 */
export const USER_ROLES: UserRole[] = ['member', 'admin', 'super_admin'] as const

/**
 * Role hierarchy levels
 *
 * Higher numbers indicate more privileges.
 * Used for hierarchical role checking where higher-level roles
 * can access resources restricted to lower-level roles.
 */
export const ROLE_HIERARCHY: Record<UserRole, number> = {
  member: 1,
  admin: 2,
  super_admin: 3,
} as const

/**
 * Human-readable role labels
 *
 * Maps role identifiers to display-friendly names for UI rendering.
 */
export const ROLE_LABELS: Record<UserRole, string> = {
  member: 'Member',
  admin: 'Administrator',
  super_admin: 'Super Administrator',
} as const
