import { createClient } from '@libsql/client/web'

export const TURSO_DATABASE_URL = import.meta.env.TURSO_DATABASE_URL
export const TURSO_AUTH_TOKEN = import.meta.env.TURSO_AUTH_TOKEN

// Generated by Copilot
if (!TURSO_DATABASE_URL) {
  throw new Error('TURSO_DATABASE_URL must be set in the environment variables.')
}
if (!TURSO_AUTH_TOKEN) {
  throw new Error('TURSO_AUTH_TOKEN must be set in the environment variables.')
}

const client = createClient({
  url: TURSO_DATABASE_URL,
  authToken: TURSO_AUTH_TOKEN,
})

export default client
