name: Playwright Tests
on:
  push:
    branches: [primary, develop]
  pull_request:
    branches: [primary, develop]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup environment variables
        run: |
          echo "Setting up environment variables..."

          # Set Clerk environment variables with fallbacks
          if [ -n "${{ secrets.PUBLIC_CLERK_PUBLISHABLE_KEY }}" ]; then
            echo "PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> $GITHUB_ENV
            echo "✅ Using provided PUBLIC_CLERK_PUBLISHABLE_KEY"
          else
            echo "PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Y2xlcmsuY29tJA" >> $GITHUB_ENV
            echo "⚠️  Using fallback PUBLIC_CLERK_PUBLISHABLE_KEY"
          fi

          if [ -n "${{ secrets.CLERK_SECRET_KEY }}" ]; then
            echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> $GITHUB_ENV
            echo "✅ Using provided CLERK_SECRET_KEY"
          else
            echo "CLERK_SECRET_KEY=sk_test_Y2xlcmsuY29tJA" >> $GITHUB_ENV
            echo "⚠️  Using fallback CLERK_SECRET_KEY"
          fi

          # Set other required environment variables for CI
          echo "CI=true" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV

      - name: Verify environment setup
        run: |
          echo "Environment variables check:"
          echo "PUBLIC_CLERK_PUBLISHABLE_KEY: ${PUBLIC_CLERK_PUBLISHABLE_KEY:0:20}..."
          echo "CLERK_SECRET_KEY: ${CLERK_SECRET_KEY:0:20}..."
          echo "CI: $CI"
          echo "NODE_ENV: $NODE_ENV"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers with retry
        run: |
          # Try installing with retries for better reliability
          success=false
          for i in {1..3}; do
            echo "Browser installation attempt $i..."
            
            # Clear any corrupted cache first
            rm -rf ~/.cache/ms-playwright* || true
            
            # Try to install only Chromium with system dependencies
            if npx playwright install chromium --with-deps; then
              echo "✅ Browser installation successful on attempt $i"
              success=true
              break
            else
              echo "❌ Attempt $i failed, error code: $?"
              if [ $i -eq 3 ]; then
                echo "All browser installation attempts failed"
                echo "Trying alternative installation approach..."
                
                # Try installing system browser as fallback
                sudo apt-get update
                sudo apt-get install -y chromium-browser
                
                # Check if we can use system browser
                which chromium-browser && echo "✅ System browser available as fallback"
              fi
              sleep 15
            fi
          done

          if [ "$success" != "true" ]; then
            echo "⚠️  Playwright browser installation failed, but continuing with system browser fallback"
            # Set environment variable to use system browser
            echo "PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium-browser" >> $GITHUB_ENV
          fi

      - name: Verify Playwright installation
        run: |
          echo "Verifying Playwright installation..."
          npx playwright --version

      - name: Run Playwright tests
        run: |
          echo "Starting Playwright tests..."
          npx playwright test --config=playwright.config.ts
        env:
          # Ensure environment variables are available during test execution
          PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ env.PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ env.CLERK_SECRET_KEY }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30

      - name: Upload test artifacts on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-failure-artifacts
          path: |
            test-results/
            screenshots/
            videos/
          retention-days: 7
